import type { Project } from "../lib/content-types";

export const projects: Project[] = [
  {
    slug: "distribution",
    name: "Distribution",
    oneLineValue: "把链接、图片和 bot 入口变成可追踪的分发与结算入口。",
    status: "community_pilot",
    audienceFit: ["curious_explorer", "community_participant", "builder_or_creator"],
    participationMode: ["join_community", "follow_updates", "deeper_participation"],
    externalLink: {
      label: "进入 Distribution",
      url: "https://distribution.72h.lol/distribution/",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "core",
      summary: "72hours 的归因与分发引擎，把结果回流到生态主场。",
    },
    learnRelation: {
      level: "advanced",
      summary: "适合已经看懂基础入口的人继续往更深的协作场景走。",
    },
    proofAssets: [],
    featured: true,
    priority: 1,
    iconKey: "box",
  },
  {
    slug: "sigma",
    name: "Sigma",
    oneLineValue: "围绕目标、证据、陪审和结算的规则化验证层。",
    status: "community_pilot",
    audienceFit: ["community_participant", "builder_or_creator", "deeper_learner"],
    participationMode: ["join_community", "follow_updates", "deeper_participation"],
    externalLink: {
      label: "加入社区了解 Sigma",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "用规则把参与边界、证据和授权关系整理清楚。",
    },
    learnRelation: {
      level: "prep",
      summary: "适合进入更深协作之前先建立判断框架。",
    },
    proofAssets: [],
    featured: false,
    priority: 2,
    iconKey: "beaker",
  },
  {
    slug: "proof-card-builder",
    name: "Proof Card Builder",
    oneLineValue: "把结果、成就和 mini app 输出转成可分享、可复用的 proof card。",
    status: "beta",
    audienceFit: ["new_to_crypto", "curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates", "try_now"],
    externalLink: {
      label: "加入社区了解开放进度",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "把协作结果变成更容易传播的可见凭证。",
    },
    learnRelation: {
      level: "prep",
      summary: "适合先看懂真实项目，再进入学习和构建。",
    },
    proofAssets: [],
    featured: false,
    priority: 3,
    iconKey: "check",
  },
  {
    slug: "sticker-meme-studio",
    name: "Sticker / Meme Studio",
    oneLineValue: "把一句文本或一张图快速变成可传播的 sticker / meme 资产。",
    status: "beta",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates", "try_now"],
    externalLink: {
      label: "加入社区了解开放进度",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "让生态内容以更轻量的方式流动起来。",
    },
    learnRelation: {
      level: "prep",
      summary: "适合先看懂内容流转，再进入更深构建。",
    },
    proofAssets: [],
    featured: false,
    priority: 4,
    iconKey: "spark",
  },
  {
    slug: "daily-pulse-vote",
    name: "每日脉动投票",
    oneLineValue: "把一次投票变成可回流的每日参与节奏。",
    status: "beta",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates", "try_now"],
    externalLink: {
      label: "加入社区获取开放入口",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "用固定频率把社区注意力聚拢到同一个场景里。",
    },
    learnRelation: {
      level: "prep",
      summary: "适合先理解参与节奏，再进入更深协作。",
    },
    proofAssets: [],
    featured: false,
    priority: 5,
    iconKey: "shield",
  },
  {
    slug: "72hours-control-room",
    name: "72hours",
    oneLineValue: "72hours 的控制层主场，承接入口、节奏、结算和更深参与路径。",
    status: "community_pilot",
    audienceFit: ["curious_explorer", "community_participant", "deeper_learner"],
    participationMode: ["join_community", "follow_updates", "deeper_participation"],
    externalLink: {
      label: "进入主场",
      url: "https://72hours.72h.lol",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "core",
      summary: "把社区、生态和路径串成一个统一的主入口。",
    },
    learnRelation: {
      level: "integrated",
      summary: "是学习、参与和协作的总入口，而不是单独的功能页。",
    },
    proofAssets: [],
    featured: false,
    priority: 6,
    iconKey: "check",
  },
  {
    slug: "coop-raid-room",
    name: "Co-op Raid Room",
    oneLineValue: "围绕协作冲刺、任务分工和实时反馈的共建空间。",
    status: "coming_soon",
    audienceFit: ["community_participant", "builder_or_creator"],
    participationMode: ["join_community", "follow_updates"],
    externalLink: {
      label: "加入社区看开放进度",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "把临时协作和阶段性任务放到同一间房间里。",
    },
    learnRelation: {
      level: "prep",
      summary: "适合先跟上社区节奏，再进入协作任务。",
    },
    proofAssets: [],
    featured: false,
    priority: 7,
    iconKey: "box",
  },
  {
    slug: "meme-court",
    name: "Meme Court",
    oneLineValue: "围绕内容评审、公开讨论和轻量共识形成的互动空间。",
    status: "coming_soon",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates"],
    externalLink: {
      label: "加入社区看开放进度",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "让内容判断和共识讨论有一个明确场域。",
    },
    learnRelation: {
      level: "prep",
      summary: "适合先看懂生态，再进入内容评审协作。",
    },
    proofAssets: [],
    featured: false,
    priority: 8,
    iconKey: "beaker",
  },
  {
    slug: "chain-relay-canvas",
    name: "Chain Relay Canvas",
    oneLineValue: "围绕接力创作、链式协作和可视化过程的连续画布。",
    status: "coming_soon",
    audienceFit: ["builder_or_creator", "deeper_learner"],
    participationMode: ["join_community", "follow_updates"],
    externalLink: {
      label: "加入社区看开放进度",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "把连续协作变成可跟踪、可回放的过程。",
    },
    learnRelation: {
      level: "advanced",
      summary: "适合已经准备进入更深协作与构建的人。",
    },
    proofAssets: [],
    featured: false,
    priority: 9,
    iconKey: "relay",
  },
];
