import type { Project } from "../lib/content-types";
import type { Locale } from "../lib/locale";
import { localized } from "../lib/locale";

const projectsZh: Project[] = [
  {
    slug: "distribution",
    name: "Distribution",
    oneLineValue: "把链接、图片和 Bot 入口变成可追踪分发。",
    summary: "把外部分发重新收束到生态主场，是当前最值得先看的入口之一。",
    detailIntro: "如果你只想先理解 72hours 的入口结构，从这里开始最快。",
    category: "main_entry",
    status: "community_pilot",
    audienceFit: ["curious_explorer", "community_participant", "builder_or_creator"],
    participationMode: ["join_community", "follow_updates", "deeper_participation"],
    externalLink: {
      label: "进入",
      url: "https://distribution.72h.lol/distribution/",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "core",
      summary: "回流到生态主场。",
    },
    learnRelation: {
      level: "advanced",
      summary: "先看入口，再进协作。",
    },
    proofAssets: [],
    featured: true,
    priority: 1,
    iconKey: "box",
    signals: [
      { tone: "hot", label: "高关注" },
      { tone: "core", label: "主入口" },
    ],
  },
  {
    slug: "wan",
    name: "WAN",
    oneLineValue: "浏览器优先的安全接入控制台，处理访问、会话、节点与订阅。",
    summary: "Web 是完整控制台；原生端只保留 VPN 服务和 72H 充值。",
    detailIntro: "适合需要直接上手的人，先从浏览器进入即可，不必先理解全部生态。",
    category: "new_launch",
    status: "live",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["try_now", "follow_updates"],
    externalLink: {
      label: "进入",
      url: "https://wan.lat",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "把安全访问、会话和节点管理落到实际使用。",
    },
    learnRelation: {
      level: "prep",
      summary: "先上手浏览器主控台，再看原生端边界。",
    },
    proofAssets: [],
    featured: false,
    priority: 2,
    logoSrc: "/brands/wan-icon.png",
    logoAlt: "WAN icon",
    brandStripSrc: "/brands/wan-lockup.png",
    brandStripAlt: "WAN brand logo",
    signals: [
      { tone: "new", label: "新上线" },
      { tone: "guide", label: "Web 主控台" },
    ],
  },
  {
    slug: "sigma",
    name: "Sigma",
    oneLineValue: "围绕目标、证据和结算的验证层。",
    category: "tools",
    status: "community_pilot",
    audienceFit: ["community_participant", "builder_or_creator", "deeper_learner"],
    participationMode: ["join_community", "follow_updates", "deeper_participation"],
    externalLink: {
      label: "查看",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "整理边界、证据和授权。",
    },
    learnRelation: {
      level: "prep",
      summary: "先建立判断框架。",
    },
    proofAssets: [],
    featured: false,
    priority: 2,
    iconKey: "beaker",
  },
  {
    slug: "proof-card-builder",
    name: "Proof Card Builder",
    oneLineValue: "把结果转成可分享的证明卡。",
    category: "tools",
    status: "beta",
    audienceFit: ["new_to_crypto", "curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates", "try_now"],
    externalLink: {
      label: "查看",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "把结果变成凭证。",
    },
    learnRelation: {
      level: "prep",
      summary: "先看懂项目，再进构建。",
    },
    proofAssets: [],
    featured: false,
    priority: 3,
    iconKey: "check",
  },
  {
    slug: "sticker-meme-studio",
    name: "Meme Studio",
    oneLineValue: "把文本或图片快速做成传播素材。",
    category: "tools",
    status: "beta",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates", "try_now"],
    externalLink: {
      label: "查看",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "让内容更易传播。",
    },
    learnRelation: {
      level: "prep",
      summary: "先看内容流转。",
    },
    proofAssets: [],
    featured: false,
    priority: 4,
    iconKey: "spark",
  },
  {
    slug: "daily-pulse-vote",
    name: "每日脉动投票",
    oneLineValue: "把投票变成每日参与节奏。",
    category: "tools",
    status: "beta",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates", "try_now"],
    externalLink: {
      label: "查看",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "聚合社区注意力。",
    },
    learnRelation: {
      level: "prep",
      summary: "先理解参与节奏。",
    },
    proofAssets: [],
    featured: false,
    priority: 5,
    iconKey: "shield",
  },
  {
    slug: "72hours-control-room",
    name: "72hours",
    oneLineValue: "72hours 主场，承接入口、使用与参与。",
    summary: "生态主场，负责承接入口、使用、参与与学习。",
    detailIntro: "当你需要总入口和全局视图时，看这里。",
    category: "main_entry",
    status: "community_pilot",
    audienceFit: ["curious_explorer", "community_participant", "deeper_learner"],
    participationMode: ["join_community", "follow_updates", "deeper_participation"],
    externalLink: {
      label: "进入",
      url: "https://72hours.72h.lol",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "core",
      summary: "串起入口、使用和学习。",
    },
    learnRelation: {
      level: "integrated",
      summary: "学习、参与、协作的总入口。",
    },
    proofAssets: [],
    featured: false,
    priority: 6,
    iconKey: "check",
    signals: [
      { tone: "core", label: "生态核心" },
      { tone: "guide", label: "总入口" },
    ],
  },
  {
    slug: "coop-raid-room",
    name: "Co-op Raid Room",
    oneLineValue: "围绕协作冲刺、分工与反馈。",
    category: "coming_soon",
    status: "coming_soon",
    audienceFit: ["community_participant", "builder_or_creator"],
    participationMode: ["join_community", "follow_updates"],
    externalLink: {
      label: "查看",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "把任务放到同一处。",
    },
    learnRelation: {
      level: "prep",
      summary: "先跟上社区节奏。",
    },
    proofAssets: [],
    featured: false,
    priority: 7,
    iconKey: "box",
  },
  {
    slug: "meme-court",
    name: "Meme Court",
    oneLineValue: "用于内容评审的轻量共识空间。",
    category: "coming_soon",
    status: "coming_soon",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates"],
    externalLink: {
      label: "查看",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "给判断一个场域。",
    },
    learnRelation: {
      level: "prep",
      summary: "先看懂生态，再进评审。",
    },
    proofAssets: [],
    featured: false,
    priority: 8,
    iconKey: "beaker",
  },
  {
    slug: "chain-relay-canvas",
    name: "Chain Relay Canvas",
    oneLineValue: "承接接力创作与协作过程的画布。",
    category: "coming_soon",
    status: "coming_soon",
    audienceFit: ["builder_or_creator", "deeper_learner"],
    participationMode: ["join_community", "follow_updates"],
    externalLink: {
      label: "查看",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "把连续协作变成过程。",
    },
    learnRelation: {
      level: "advanced",
      summary: "适合进入更深协作。",
    },
    proofAssets: [],
    featured: false,
    priority: 9,
    iconKey: "relay",
  },
];

const projectsEn: Project[] = [
  {
    slug: "distribution",
    name: "Distribution",
    oneLineValue: "Turn links, images, and bot entries into traceable distribution.",
    summary: "Pulls outside distribution back into the ecosystem main stage and is one of the best places to start.",
    detailIntro: "If you want to understand the 72hours entry structure fast, start here.",
    category: "main_entry",
    status: "community_pilot",
    audienceFit: ["curious_explorer", "community_participant", "builder_or_creator"],
    participationMode: ["join_community", "follow_updates", "deeper_participation"],
    externalLink: {
      label: "Enter",
      url: "https://distribution.72h.lol/distribution/",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "core",
      summary: "Flows back to the ecosystem main stage.",
    },
    learnRelation: {
      level: "advanced",
      summary: "See the entry first, then join the collaboration.",
    },
    proofAssets: [],
    featured: true,
    priority: 1,
    iconKey: "box",
    signals: [
      { tone: "hot", label: "High attention" },
      { tone: "core", label: "Primary entry" },
    ],
  },
  {
    slug: "wan",
    name: "WAN",
    oneLineValue: "Browser-first secure access console for sessions, nodes, subscription, and control.",
    summary: "The web surface is the full control console; native clients stay limited to VPN service and 72H recharge.",
    detailIntro: "Best for people who want to get into the product immediately without learning the whole ecosystem first.",
    category: "new_launch",
    status: "live",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["try_now", "follow_updates"],
    externalLink: {
      label: "Enter",
      url: "https://wan.lat",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "Turns secure access, sessions, and node management into real usage.",
    },
    learnRelation: {
      level: "prep",
      summary: "Start with the browser console, then understand native-client scope.",
    },
    proofAssets: [],
    featured: false,
    priority: 2,
    logoSrc: "/brands/wan-icon.png",
    logoAlt: "WAN icon",
    brandStripSrc: "/brands/wan-lockup.png",
    brandStripAlt: "WAN brand logo",
    signals: [
      { tone: "new", label: "New launch" },
      { tone: "guide", label: "Web console" },
    ],
  },
  {
    slug: "sigma",
    name: "Sigma",
    oneLineValue: "Verification for goals, evidence, and settlement.",
    category: "tools",
    status: "community_pilot",
    audienceFit: ["community_participant", "builder_or_creator", "deeper_learner"],
    participationMode: ["join_community", "follow_updates", "deeper_participation"],
    externalLink: {
      label: "View",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "Organizes boundaries, evidence, and authorization.",
    },
    learnRelation: {
      level: "prep",
      summary: "Build the judgment framework first.",
    },
    proofAssets: [],
    featured: false,
    priority: 2,
    iconKey: "beaker",
  },
  {
    slug: "proof-card-builder",
    name: "Proof Card Builder",
    oneLineValue: "Turn results into shareable proof cards.",
    category: "tools",
    status: "beta",
    audienceFit: ["new_to_crypto", "curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates", "try_now"],
    externalLink: {
      label: "View",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "Turns results into credentials.",
    },
    learnRelation: {
      level: "prep",
      summary: "Understand the project before building.",
    },
    proofAssets: [],
    featured: false,
    priority: 3,
    iconKey: "check",
  },
  {
    slug: "sticker-meme-studio",
    name: "Meme Studio",
    oneLineValue: "Quickly turn text or images into shareable assets.",
    category: "tools",
    status: "beta",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates", "try_now"],
    externalLink: {
      label: "View",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "Makes content easier to spread.",
    },
    learnRelation: {
      level: "prep",
      summary: "Understand the content flow first.",
    },
    proofAssets: [],
    featured: false,
    priority: 4,
    iconKey: "spark",
  },
  {
    slug: "daily-pulse-vote",
    name: "Daily Pulse Vote",
    oneLineValue: "Turn voting into a daily participation rhythm.",
    category: "tools",
    status: "beta",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates", "try_now"],
    externalLink: {
      label: "View",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "Aggregates community attention.",
    },
    learnRelation: {
      level: "prep",
      summary: "Understand the participation rhythm first.",
    },
    proofAssets: [],
    featured: false,
    priority: 5,
    iconKey: "shield",
  },
  {
    slug: "72hours-control-room",
    name: "72hours",
    oneLineValue: "The 72hours main stage for entry, use, and participation.",
    summary: "The ecosystem main stage that holds entry, use, participation, and learning together.",
    detailIntro: "Go here when you need the broadest view of the ecosystem.",
    category: "main_entry",
    status: "community_pilot",
    audienceFit: ["curious_explorer", "community_participant", "deeper_learner"],
    participationMode: ["join_community", "follow_updates", "deeper_participation"],
    externalLink: {
      label: "Enter",
      url: "https://72hours.72h.lol",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "core",
      summary: "Connects entry, use, and learning.",
    },
    learnRelation: {
      level: "integrated",
      summary: "The main entrance for learning, participation, and collaboration.",
    },
    proofAssets: [],
    featured: false,
    priority: 6,
    iconKey: "check",
    signals: [
      { tone: "core", label: "Ecosystem core" },
      { tone: "guide", label: "Main stage" },
    ],
  },
  {
    slug: "coop-raid-room",
    name: "Co-op Raid Room",
    oneLineValue: "Around collaboration sprints, task splits, and feedback.",
    category: "coming_soon",
    status: "coming_soon",
    audienceFit: ["community_participant", "builder_or_creator"],
    participationMode: ["join_community", "follow_updates"],
    externalLink: {
      label: "View",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "Places tasks in one place.",
    },
    learnRelation: {
      level: "prep",
      summary: "Keep up with the community rhythm first.",
    },
    proofAssets: [],
    featured: false,
    priority: 7,
    iconKey: "box",
  },
  {
    slug: "meme-court",
    name: "Meme Court",
    oneLineValue: "A lightweight consensus space for content review.",
    category: "coming_soon",
    status: "coming_soon",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates"],
    externalLink: {
      label: "View",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "Gives judgment a place to happen.",
    },
    learnRelation: {
      level: "prep",
      summary: "Understand the ecosystem before entering review.",
    },
    proofAssets: [],
    featured: false,
    priority: 8,
    iconKey: "beaker",
  },
  {
    slug: "chain-relay-canvas",
    name: "Chain Relay Canvas",
    oneLineValue: "A canvas around relay creation and collaborative process.",
    category: "coming_soon",
    status: "coming_soon",
    audienceFit: ["builder_or_creator", "deeper_learner"],
    participationMode: ["join_community", "follow_updates"],
    externalLink: {
      label: "View",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "Turns continuous collaboration into a process.",
    },
    learnRelation: {
      level: "advanced",
      summary: "Suitable for deeper collaboration.",
    },
    proofAssets: [],
    featured: false,
    priority: 9,
    iconKey: "relay",
  },
];

export const projects = projectsZh;

export function getProjects(locale: Locale) {
  return localized(locale, projectsZh, projectsEn);
}
