import type { Project, ProjectAppCategory, ProjectChain, ProjectDevelopmentStage } from "../lib/content-types";
import type { Locale } from "../lib/locale";
import { localized } from "../lib/locale";

const projectsZh: Project[] = [
  {
    slug: "distribution",
    name: "Distribution",
    oneLineValue: "把链接、图片和 Bot 入口变成可追踪分发。",
    summary: "把外部分发重新收束到生态主场，是当前的重要入口之一。",
    detailIntro: "这是理解 72hours 入口结构的主要入口。",
    category: "main_entry",
    status: "community_pilot",
    audienceFit: ["curious_explorer", "community_participant", "builder_or_creator"],
    participationMode: ["join_community", "follow_updates", "deeper_participation"],
    externalLink: {
      label: "进入",
      url: "https://distribution.72h.lol/distribution/",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "core",
      summary: "回流到生态主场。",
    },
    learnRelation: {
      level: "advanced",
      summary: "协作前先理解项目结构。",
    },
    proofAssets: [],
    featured: true,
    priority: 1,
    iconKey: "box",
    signals: [
      { tone: "hot", label: "高关注" },
      { tone: "core", label: "主入口" },
    ],
  },
  {
    slug: "wan",
    name: "WAN",
    oneLineValue: "浏览器优先的安全接入入口，处理访问、会话、节点与订阅。",
    summary: "Web 是完整入口；原生端只保留 VPN 服务和 72H 充值。",
    detailIntro: "适合直接使用的浏览器主控台，Web 是完整入口。",
    category: "new_launch",
    status: "live",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["try_now", "follow_updates"],
    externalLink: {
      label: "进入",
      url: "https://wan.lat",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "把安全访问、会话和节点管理落到实际使用。",
    },
    learnRelation: {
      level: "prep",
      summary: "浏览器主控台与原生端边界清晰。",
    },
    proofAssets: [],
    featured: false,
    priority: 2,
    logoSrc: "/brands/wan-icon.png",
    logoAlt: "WAN icon",
    brandStripSrc: "/brands/wan-lockup.webp",
    brandStripAlt: "WAN brand logo",
    signals: [
      { tone: "new", label: "新上线" },
      { tone: "guide", label: "Web 主控台" },
    ],
  },
  {
    slug: "sigma",
    name: "Sigma",
    oneLineValue: "围绕目标、证据和结算的验证层。",
    category: "tools",
    status: "community_pilot",
    audienceFit: ["community_participant", "builder_or_creator", "deeper_learner"],
    participationMode: ["join_community", "follow_updates", "deeper_participation"],
    externalLink: {
      label: "查看",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "整理边界、证据和授权。",
    },
    learnRelation: {
      level: "prep",
      summary: "先建立判断框架。",
    },
    proofAssets: [],
    featured: false,
    priority: 2,
    iconKey: "beaker",
  },
  {
    slug: "proof-card-builder",
    name: "Proof Card Builder",
    oneLineValue: "把结果转成可分享的证明卡。",
    category: "tools",
    status: "beta",
    audienceFit: ["new_to_crypto", "curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates", "try_now"],
    externalLink: {
      label: "查看",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "把结果变成凭证。",
    },
    learnRelation: {
      level: "prep",
      summary: "项目理解与构建协作。",
    },
    proofAssets: [],
    featured: false,
    priority: 3,
    iconKey: "check",
  },
  {
    slug: "sticker-meme-studio",
    name: "Meme Studio",
    oneLineValue: "把文本或图片快速做成传播素材。",
    category: "tools",
    status: "beta",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates", "try_now"],
    externalLink: {
      label: "查看",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "让内容更易传播。",
    },
    learnRelation: {
      level: "prep",
      summary: "内容流转的基础界面。",
    },
    proofAssets: [],
    featured: false,
    priority: 4,
    iconKey: "spark",
  },
  {
    slug: "daily-pulse-vote",
    name: "每日脉动投票",
    oneLineValue: "把投票变成每日参与节奏。",
    category: "tools",
    status: "beta",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates", "try_now"],
    externalLink: {
      label: "查看",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "聚合社区注意力。",
    },
    learnRelation: {
      level: "prep",
      summary: "社区节奏与协作结构。",
    },
    proofAssets: [],
    featured: false,
    priority: 5,
    iconKey: "shield",
  },
  {
    slug: "72hours-control-room",
    name: "72hours",
    oneLineValue: "72hours 主场，承接入口、使用与参与。",
    summary: "生态主场，负责承接入口、使用、参与与学习。",
    detailIntro: "适合需要总入口和全局视图的用户。",
    category: "main_entry",
    status: "community_pilot",
    audienceFit: ["curious_explorer", "community_participant", "deeper_learner"],
    participationMode: ["join_community", "follow_updates", "deeper_participation"],
    externalLink: {
      label: "进入",
      url: "https://72h.lol",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "core",
      summary: "串起入口、使用和学习。",
    },
    learnRelation: {
      level: "integrated",
      summary: "学习、参与与协作的总入口。",
    },
    proofAssets: [],
    featured: false,
    priority: 6,
    iconKey: "check",
    signals: [
      { tone: "core", label: "生态核心" },
      { tone: "guide", label: "总入口" },
    ],
  },
  {
    slug: "multi-millionaire",
    name: "multi-millionaire",
    oneLineValue: "multi-millionaire 候补说明与身份规则参考，真实锁仓和奖励领取暂未开放。",
    summary: "当前仅保留候补与规则说明，不开放真实链上锁仓、席位配置或奖励领取。",
    detailIntro: "适合先阅读规则、风险边界和未来开放条件。",
    category: "main_entry",
    status: "community_pilot",
    audienceFit: ["curious_explorer", "community_participant", "deeper_learner"],
    participationMode: ["follow_updates", "join_community"],
    externalLink: {
      label: "进入",
      url: "/capital/multi-millionaire",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "仅作为规则参考和候补入口，不开放配置。",
    },
    learnRelation: {
      level: "prep",
      summary: "先理解规则、边界与未开放状态。",
    },
    proofAssets: [],
    featured: false,
    priority: 7,
    iconKey: "shield",
    signals: [
      { tone: "guide", label: "候补" },
      { tone: "guide", label: "未开放" },
    ],
  },
  {
    slug: "coop-raid-room",
    name: "Co-op Raid Room",
    oneLineValue: "围绕协作冲刺、分工与反馈。",
    category: "coming_soon",
    status: "coming_soon",
    audienceFit: ["community_participant", "builder_or_creator"],
    participationMode: ["join_community", "follow_updates"],
    externalLink: {
      label: "查看",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "把任务放到同一处。",
    },
    learnRelation: {
      level: "prep",
      summary: "社区节奏与协作结构。",
    },
    proofAssets: [],
    featured: false,
    priority: 7,
    iconKey: "box",
  },
  {
    slug: "meme-court",
    name: "Meme Court",
    oneLineValue: "用于内容评审的轻量共识空间。",
    category: "coming_soon",
    status: "coming_soon",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates"],
    externalLink: {
      label: "查看",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "给判断一个场域。",
    },
    learnRelation: {
      level: "prep",
      summary: "生态理解与评审结构。",
    },
    proofAssets: [],
    featured: false,
    priority: 8,
    iconKey: "beaker",
  },
  {
    slug: "chain-relay-canvas",
    name: "Chain Relay Canvas",
    oneLineValue: "承接接力创作与协作过程的画布。",
    category: "coming_soon",
    status: "coming_soon",
    audienceFit: ["builder_or_creator", "deeper_learner"],
    participationMode: ["join_community", "follow_updates"],
    externalLink: {
      label: "查看",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "把连续协作变成过程。",
    },
    learnRelation: {
      level: "advanced",
      summary: "适合进入更深协作。",
    },
    proofAssets: [],
    featured: false,
    priority: 9,
    iconKey: "relay",
  },
];

const projectsEn: Project[] = [
  {
    slug: "distribution",
    name: "Distribution",
    oneLineValue: "Turn links, images, and bot entries into traceable distribution.",
    summary: "Pulls outside distribution back into the ecosystem main stage and is one of the key entry points.",
    detailIntro: "The fastest way to understand the 72hours entry structure.",
    category: "main_entry",
    status: "community_pilot",
    audienceFit: ["curious_explorer", "community_participant", "builder_or_creator"],
    participationMode: ["join_community", "follow_updates", "deeper_participation"],
    externalLink: {
      label: "Enter",
      url: "https://distribution.72h.lol/distribution/",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "core",
      summary: "Flows back to the ecosystem main stage.",
    },
    learnRelation: {
      level: "advanced",
      summary: "Entry structure and collaboration layer.",
    },
    proofAssets: [],
    featured: true,
    priority: 1,
    iconKey: "box",
    signals: [
      { tone: "hot", label: "High attention" },
      { tone: "core", label: "Primary entry" },
    ],
  },
  {
    slug: "wan",
    name: "WAN",
    oneLineValue: "Browser-led secure access entry for sessions, nodes, and subscription.",
    summary: "The web entry is the full service home; native clients stay limited to VPN service and 72H recharge.",
    detailIntro: "Best for people who want to use the browser entry immediately, with a clear native-client boundary.",
    category: "new_launch",
    status: "live",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["try_now", "follow_updates"],
    externalLink: {
      label: "Enter",
      url: "https://wan.lat",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "Turns secure access, sessions, and node management into real usage.",
    },
    learnRelation: {
      level: "prep",
      summary: "Browser entry and native-client boundaries stay clear.",
    },
    proofAssets: [],
    featured: false,
    priority: 2,
    logoSrc: "/brands/wan-icon.png",
    logoAlt: "WAN icon",
    brandStripSrc: "/brands/wan-lockup.webp",
    brandStripAlt: "WAN brand logo",
    signals: [
      { tone: "new", label: "New launch" },
      { tone: "guide", label: "Web entry" },
    ],
  },
  {
    slug: "sigma",
    name: "Sigma",
    oneLineValue: "Verification for goals, evidence, and settlement.",
    category: "tools",
    status: "community_pilot",
    audienceFit: ["community_participant", "builder_or_creator", "deeper_learner"],
    participationMode: ["join_community", "follow_updates", "deeper_participation"],
    externalLink: {
      label: "View",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "Organizes boundaries, evidence, and authorization.",
    },
    learnRelation: {
      level: "prep",
      summary: "Judgment framework and verification layer.",
    },
    proofAssets: [],
    featured: false,
    priority: 2,
    iconKey: "beaker",
  },
  {
    slug: "proof-card-builder",
    name: "Proof Card Builder",
    oneLineValue: "Turn results into shareable proof cards.",
    category: "tools",
    status: "beta",
    audienceFit: ["new_to_crypto", "curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates", "try_now"],
    externalLink: {
      label: "View",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "Turns results into credentials.",
    },
    learnRelation: {
      level: "prep",
      summary: "Project understanding and building layer.",
    },
    proofAssets: [],
    featured: false,
    priority: 3,
    iconKey: "check",
  },
  {
    slug: "sticker-meme-studio",
    name: "Meme Studio",
    oneLineValue: "Quickly turn text or images into shareable assets.",
    category: "tools",
    status: "beta",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates", "try_now"],
    externalLink: {
      label: "View",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "Makes content easier to spread.",
    },
    learnRelation: {
      level: "prep",
      summary: "Content flow and distribution layer.",
    },
    proofAssets: [],
    featured: false,
    priority: 4,
    iconKey: "spark",
  },
  {
    slug: "daily-pulse-vote",
    name: "Daily Pulse Vote",
    oneLineValue: "Turn voting into a daily participation rhythm.",
    category: "tools",
    status: "beta",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates", "try_now"],
    externalLink: {
      label: "View",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "Aggregates community attention.",
    },
    learnRelation: {
      level: "prep",
      summary: "Participation rhythm and community layer.",
    },
    proofAssets: [],
    featured: false,
    priority: 5,
    iconKey: "shield",
  },
  {
    slug: "72hours-control-room",
    name: "72hours",
    oneLineValue: "The 72hours main stage for entry, use, and participation.",
    summary: "The ecosystem main stage that holds entry, use, participation, and learning together.",
    detailIntro: "Go here when you need the broadest view of the ecosystem.",
    category: "main_entry",
    status: "community_pilot",
    audienceFit: ["curious_explorer", "community_participant", "deeper_learner"],
    participationMode: ["join_community", "follow_updates", "deeper_participation"],
    externalLink: {
      label: "Enter",
      url: "https://72h.lol",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "core",
      summary: "Connects entry, use, and learning.",
    },
    learnRelation: {
      level: "integrated",
      summary: "The main entrance for learning, participation, and collaboration.",
    },
    proofAssets: [],
    featured: false,
    priority: 6,
    iconKey: "check",
    signals: [
      { tone: "core", label: "Ecosystem core" },
      { tone: "guide", label: "Main stage" },
    ],
  },
  {
    slug: "multi-millionaire",
    name: "multi-millionaire",
    oneLineValue: "Waitlist and identity-rule reference for multi-millionaire; real lock-up and reward claims are not open.",
    summary: "Currently a waitlist and rule note only; real on-chain lock-up, seat actions, and reward claiming are not open.",
    detailIntro: "Use this to read rules, risk boundaries, and future opening conditions first.",
    category: "main_entry",
    status: "community_pilot",
    audienceFit: ["curious_explorer", "community_participant", "deeper_learner"],
    participationMode: ["follow_updates", "join_community"],
    externalLink: {
      label: "Enter",
      url: "/capital/multi-millionaire",
      type: "app",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "Rule reference and waitlist only; configuration remains closed.",
    },
    learnRelation: {
      level: "prep",
      summary: "Review rules, boundaries, and closed status first.",
    },
    proofAssets: [],
    featured: false,
    priority: 7,
    iconKey: "shield",
    signals: [
      { tone: "guide", label: "Waitlist" },
      { tone: "guide", label: "Not open" },
    ],
  },
  {
    slug: "coop-raid-room",
    name: "Co-op Raid Room",
    oneLineValue: "Around collaboration sprints, task splits, and feedback.",
    category: "coming_soon",
    status: "coming_soon",
    audienceFit: ["community_participant", "builder_or_creator"],
    participationMode: ["join_community", "follow_updates"],
    externalLink: {
      label: "View",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "supported",
      summary: "Places tasks in one place.",
    },
    learnRelation: {
      level: "prep",
      summary: "Community rhythm and collaboration layer.",
    },
    proofAssets: [],
    featured: false,
    priority: 7,
    iconKey: "box",
  },
  {
    slug: "meme-court",
    name: "Meme Court",
    oneLineValue: "A lightweight consensus space for content check.",
    category: "coming_soon",
    status: "coming_soon",
    audienceFit: ["curious_explorer", "community_participant"],
    participationMode: ["join_community", "follow_updates"],
    externalLink: {
      label: "View",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "Gives judgment a place to happen.",
    },
    learnRelation: {
      level: "prep",
      summary: "Understand the ecosystem before entering check.",
    },
    proofAssets: [],
    featured: false,
    priority: 8,
    iconKey: "beaker",
  },
  {
    slug: "chain-relay-canvas",
    name: "Chain Relay Canvas",
    oneLineValue: "A canvas around relay creation and collaborative process.",
    category: "coming_soon",
    status: "coming_soon",
    audienceFit: ["builder_or_creator", "deeper_learner"],
    participationMode: ["join_community", "follow_updates"],
    externalLink: {
      label: "View",
      url: "/join",
      type: "community",
      isOfficial: true,
    },
    hoursRelation: {
      level: "adjacent",
      summary: "Turns continuous collaboration into a process.",
    },
    learnRelation: {
      level: "advanced",
      summary: "Suitable for deeper collaboration.",
    },
    proofAssets: [],
    featured: false,
    priority: 9,
    iconKey: "relay",
  },
];

export const projects = projectsZh;

const projectDiscoveryMeta: Record<
  string,
  {
    appCategories: ProjectAppCategory[];
    chains: ProjectChain[];
    developmentStage: ProjectDevelopmentStage;
    isInvestable?: boolean;
    heroImageSrc?: string;
    heroImageAlt?: string;
  }
> = {
  distribution: {
    chains: ["TON"],
    appCategories: ["tool", "social"],
    developmentStage: "live",
  },
  wan: {
    chains: ["TON"],
    appCategories: ["tool"],
    developmentStage: "new",
    isInvestable: true,
  },
  sigma: {
    chains: ["TON"],
    appCategories: ["tool"],
    developmentStage: "building",
  },
  "proof-card-builder": {
    chains: ["TON"],
    appCategories: ["tool", "content"],
    developmentStage: "building",
  },
  "sticker-meme-studio": {
    chains: ["TON"],
    appCategories: ["content"],
    developmentStage: "building",
  },
  "daily-pulse-vote": {
    chains: ["TON"],
    appCategories: ["social"],
    developmentStage: "building",
  },
  "72hours-control-room": {
    chains: ["TON"],
    appCategories: ["social"],
    developmentStage: "investable",
    isInvestable: true,
  },
  "multi-millionaire": {
    chains: ["TON"],
    appCategories: ["capital"],
    developmentStage: "building",
    isInvestable: false,
  },
  "coop-raid-room": {
    chains: ["TON"],
    appCategories: ["game", "social"],
    developmentStage: "building",
  },
  "meme-court": {
    chains: ["TON"],
    appCategories: ["game", "content"],
    developmentStage: "building",
  },
  "chain-relay-canvas": {
    chains: ["TON"],
    appCategories: ["tool", "content"],
    developmentStage: "building",
  },
};

function withDiscoveryMeta(projectList: Project[]) {
  return projectList.map((project) => {
    const meta = projectDiscoveryMeta[project.slug];

    if (!meta) {
      return {
        chains: ["TON"] as ProjectChain[],
        appCategories: ["tool"] as ProjectAppCategory[],
        developmentStage: project.status === "live" ? "live" as const : "building" as const,
        ...project,
      };
    }

    return {
      ...project,
      ...meta,
    };
  });
}

export function getProjects(locale: Locale) {
  return withDiscoveryMeta(localized(locale, projectsZh, projectsEn));
}
